### ISSUE TITLE
First run - undefined index statuses

### ISSUE THREAD

**Issue by TomasVotruba** [petrvacha/rednoi#5]
![image](https://user-images.githubusercontent.com/924196/28242615-8e43fe5e-69b0-11e7-80c3-ffaf1271e218.png)

**Comment by TomasVotruba** [comment]
I only completed ...

```yml
parameters:
    twitter.queries:
        - "pehapkari"
```


and it works. Thank you!
